### ISSUE TITLE
Definir a identidade visual do aplicativo e do sistema web

### ISSUE THREAD

**Issue by MBatistussi** [Processos-de-software-2016-2/UX#5]

**Comment by paulalps** [comment]
Pelo que eu andei olhando, o melhor a fazer é definir uma hierarquia sendo dividida em: 
     \* Texto grande e grande contraste de cor – Para mostrar o cabeçário do app;
     \* Próximo texto grande – Para mostrar um importante detalhe, no caso o nome de quem mandou a mensagem. É um título do item mensagem;
     \* Texto menor – A primeira linha ou duas abaixo do nome vem o início da mensagem. É o conteúdo que descreve o item;
     \* Espaçamento e alinhamento – Para separar as threads, os itens.
Isso para o usuário se sentir confortável ao navegar no app e poder separar bem os conteúdos. 

Uma coisa que acaba atordoando o usuário é a quantidade de informação disponibilizada na tela e a forma como ela é exposta, com isso temos que tentar deixar o mais simples possível sem deixar de ser atraente.  Uma imagem grande vai ser melhor que várias pequenas, fundos coloridos ou com informações são desnecessários.

Existe uma ideia chamada design Bauhaus que diz que os ícones ao invés de seguirem a regra do mundo real (textura e proporção)  devem ser supérfluos, sem textura, sem reflexo e sem sombras.
Então devemos usar cores vivas mas sem sombras em um layout limpo e direto.
