### ISSUE TITLE
Pesquisar técnicas/ferramentas para prototipagem de telas Android

### ISSUE THREAD

**Issue by jmatiasn** [Processos-de-software-2016-2/UX#8]

**Comment by fernandachacon** [comment]
**Ferramentas**

_Balsamiq_ [https://balsamiq.com/] é uma ferramenta free, pode ser usada online ou pode ser feito o download. Ela se aproxima de desenhos feitos a mão. Pode ser usada para projetar interfaces para aplicações web e mobile. De fácil e rápido uso, a fidelidade dos componentes da ferramenta é baixa com os usados nas aplicações.

_Pencil_ [http://pencil.evolus.vn/] é um ferramenta free, para ser usada é preciso fazer o download. É parecida com o balsamiq, mas o nível de fidelidade com os componentes é maior. Pode ser usada também para projetar interfaces web e mobile e seu uso é fácil e rápido também.

_Draw.io_ [https://www.draw.io/] é uma ferramenta de uso simples e fácil, seu uso é online e permite a integração com o google drive e pode ser feita a edição ao mesmo tempo de várias pessoas da equipe. É similiar ao balsamiq, porém tem um maior nível de fidelidade. Pode ser usada para a criação de telas para aplicações web e mobile.

_Justinmind_ [https://www.justinmind.com/] é uma ferramenta free, pode ser usada para projetar interfaces web e mobile. Os componentes se aproximam mais da realidade dos sites e aplicativos. O uso é um pouco mais complicado que o do balsamiq, porém não é difícil, precisa de um pouco mais de prática. Uma coisa interessante é que você pode contruir as telas e rodar como funciona o fluxo entre elas.

As ferramentas que eu analisei estão no link abaixo e essas que eu descrevi são as que achei interessantes para construir as telas da aplicação, todas servem para web e mobile, facilitando assim o trabalho da equipe. 

[https://www.elegantthemes.com/blog/resources/the-top-rapid-prototyping-programs-and-techniques-for-designers]
